### ISSUE TITLE
feat: ADO.NET

### ISSUE THREAD

**Issue by KirillKurdyukov** [ydb-platform/ydb-dotnet-sdk#75]
Community [reference](https://github.com/shersh/YdbDriver/tree/master)

ADO.NET must be used with [QueryService](https://github.com/ydb-platform/ydb-api-protos/blob/master/protos/ydb_query.proto) (a.k.a API 2.0 OLTP)

Roadmap of Refactoring:

- [x] #81
- [x] #84
- [x] #88
- [x] #94 
- [x] #100
- [x] #110

Roadmap QueryService 1.0.0 / fix bugs:

- [x] #86
- [x] #82
- [x] #93
- [x] #68
- [x] #53
- [x] #66
- [x] #118
- [x] #98
- [x] #104
- [x] #106
- [x] #112
- [x] #111
- [x] [feat: push nodeId to get endpoint](https://github.com/ydb-platform/ydb-dotnet-sdk/pull/114)

Roadmap ADO.NET (Directory Driver):
- [x] #122
- [x] #123
- [x] #125
- [x] #130
- [x] #131
- [x] #133
- [x] #135
- [x] #138
- [x] #142
- [x] #143
- [ ] #150
- [x] #156
- [ ] feat: release candidate ADO.NET
- [x] #151
- [x] #160

Backlog:
- [ ] feat: logging 
- [ ] #54
- [ ] #99
- [ ] feat: make min / max size in SessionPool
- [ ] feat: ADO.NET read bytes
- [ ] feat: impl DataAdapter
